import { useState, useEffect, useCallback } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import jsPDF from "jspdf";
import { copyToClipboard, preprocessMarkdown, processConversationSummary, markdownToPDFText } from "../utils/clipboard";
import FeedCard from "../components/FeedCard";
import LoadingOverlay from "../components/LoadingOverlay";
import SummaryLoadingOverlay from "../components/SummaryLoadingOverlay";

const TranscriptView = ({ recording, transcript, summary }) => {
  const [savedRecordings, setSavedRecordings] = useState([]);
  const [editingTitles, setEditingTitles] = useState({});
  const [customTitles, setCustomTitles] = useState({});
  const [loading, setLoading] = useState(false);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [loadingMessage, setLoadingMessage] = useState('Processing...');

  const startLoading = useCallback((message = 'Processing...') => {
    setLoading(true);
    setLoadingMessage(message);
    setLoadingProgress(0);
  }, []);

  const updateProgress = useCallback((progress) => {
    setLoadingProgress(progress);
  }, []);

  const stopLoading = useCallback(() => {
    setLoading(false);
    setLoadingProgress(0);
  }, []);

  const simulateProgress = () => {
    let progress = 0;
    updateProgress(0);
    
    const interval = setInterval(() => {
      progress += Math.random() * 10;
      if (progress >= 90) {
        clearInterval(interval);
      }
      updateProgress(Math.min(progress, 90));
    }, 500);

    return () => clearInterval(interval);
  };

  const handleSummaryResult = async (recording, result, type) => {
    setSavedRecordings((prev) =>
      prev.map((r) =>
        r.filename === recording.filename
          ? { ...r, summary: result }
          : r
      )
    );

    try {
      await axios.post(
        `http://localhost:3001/recordings/${recording._id}/summary`,
        {
          summary: result,
        }
      );
      toast.success(`${type} generated and saved!`);
    } catch (error) {
      console.error(`❌ Failed to save ${type.toLowerCase()} to database:`, error);
      toast.warn(`${type} generated but failed to save to database`);
    } finally {
      stopLoading();
    }
  };

  const fetchSavedRecordings = useCallback(async () => {
    try {
      startLoading('Loading recordings...');
      const response = await axios.get("http://localhost:3001/recordings");
      setSavedRecordings(response.data.recordings);
      stopLoading();
    } catch (err) {
      console.error("Failed to fetch saved recordings:", err);
      stopLoading();
    }
  }, [startLoading, stopLoading]);

  useEffect(() => {
    fetchSavedRecordings();
  }, [fetchSavedRecordings]);

  const exportToPDF = async (summaryText, title) => {
    try {
      let processedText = summaryText;
      if (
        summaryText.includes("- The assistant") ||
        summaryText.includes("- The user") ||
        summaryText.includes("Summary of the conversation") ||
        summaryText.match(/^- .*$/m)
      ) {
        processedText = processConversationSummary(summaryText);
      } else {
        processedText = preprocessMarkdown(summaryText);
      }
      
      processedText = markdownToPDFText(processedText);
      
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.width;
      const margin = 20;
      const contentWidth = pageWidth - 2 * margin;
  
      pdf.setFontSize(24);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(99, 102, 241); // Accent color
      pdf.text("ScribeFlow", margin, 20);
  
      pdf.setDrawColor(99, 102, 241);
      pdf.setLineWidth(0.5);
      pdf.line(margin, 25, pageWidth - margin, 25);
  
      pdf.setFontSize(18);
      pdf.setTextColor(0, 0, 0);
      pdf.text(title, margin, 40);
  
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(128, 128, 128);
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, margin, 50);
  
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(0, 0, 0);
      pdf.text("Summary Insights", margin, 65);
  
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      const splitText = pdf.splitTextToSize(processedText, contentWidth);
  
      let yPosition = 75;
      const lineHeight = 7;
      const maxLinesPerPage = Math.floor((pdf.internal.pageSize.height - yPosition - 20) / lineHeight);
  
      splitText.forEach((line, index) => {
        if (yPosition > pdf.internal.pageSize.height - 20) {
          pdf.addPage();
          yPosition = 20;
        }
        pdf.text(line, margin, yPosition);
        yPosition += lineHeight;
      });
  
      const pageCount = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(9);
        pdf.setTextColor(150, 150, 150);
        pdf.text(`Page ${i} of ${pageCount} — Generated by ScribeFlow`, pageWidth / 2, pdf.internal.pageSize.height - 10, { align: "center" });
      }
  
      pdf.save(`ScribeFlow_${title.replace(/\\s+/g, "_")}.pdf`);
      toast.success("PDF exported successfully!");
    } catch (err) {
      console.error("PDF export error:", err);
      toast.error("Failed to export PDF");
    }
  };

  const clearAllRecordings = async () => {
    if (!window.confirm("Delete all recordings permanently?")) return;
    try {
      const response = await axios.get("http://localhost:3001/recordings");
      const ids = response.data.recordings.map((rec) => rec._id);
      if (ids.length === 0) return;
      await axios.post("http://localhost:3001/recordings/bulk-delete", { identifiers: ids });
      fetchSavedRecordings();
      toast.success("All recordings deleted");
    } catch (error) {
      toast.error("Failed to delete recordings");
    }
  };

  const getSummaryTitle = (summaryText, id, type = "recording") => {
    const titleKey = `${type}_${id}`;
    if (customTitles[titleKey]) return customTitles[titleKey];
    if (!summaryText) return "Content Summary";
    const text = summaryText.toLowerCase();
    if (text.includes("lesson")) return "Learning Notes";
    if (text.includes("meeting")) return "Meeting Summary";
    if (text.includes("research")) return "Research Insights";
    return "Content Summary";
  };

  if (savedRecordings.length === 0 && !loading) {
    return (
      <div style={{ textAlign: 'center', padding: '80px 20px', animation: 'fadeIn 0.5s ease' }}>
        <div style={{ fontSize: '64px', marginBottom: '24px', opacity: 0.5 }}>📂</div>
        <h2 style={{ fontSize: '1.5rem', fontWeight: '800', marginBottom: '12px' }}>No transcripts yet</h2>
        <p style={{ color: 'var(--text-tertiary)', marginBottom: '32px' }}>Your recorded or uploaded audio will appear here.</p>
        <button className="btn btn-primary" onClick={() => window.location.reload()}>Refresh List</button>
      </div>
    );
  }

  return (
    <div className="transcript-view">
      {loading && <LoadingOverlay message={loadingMessage} progress={loadingProgress} />}
      
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "32px" }}>
        <div style={{ display: "flex", gap: "12px" }}>
          <button className="btn btn-secondary btn-sm" onClick={() => fetchSavedRecordings()}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ marginRight: '6px' }}><path d="M23 4v6h-6"></path><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"></path></svg>
            Refresh
          </button>
          <button className="btn btn-outline btn-sm" onClick={clearAllRecordings} style={{ color: 'var(--color-danger)' }}>
            🗑️ Clear All
          </button>
        </div>
        <div style={{ fontSize: '0.85rem', color: 'var(--text-tertiary)' }}>
          {savedRecordings.length} items found
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        {savedRecordings.map((rec) => (
          <div key={rec._id} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <FeedCard
              avatar="📄"
              title={rec.filename}
              subtitle={new Date(rec.created).toLocaleString()}
              fullText={rec.transcript}
              metadata={[
                `${(rec.size / 1024 / 1024).toFixed(2)} MB`,
                rec.hasTranscript ? "Transcribed" : "Pending"
              ]}
              actions={
                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                  {!rec.hasTranscript && (
                    <button className="btn btn-primary btn-sm" onClick={() => transcript.transcribeRecording(rec).then(() => fetchSavedRecordings())}>
                      ✨ Transcribe
                    </button>
                  )}
                  {rec.hasTranscript && (
                    <>
                      <button className="btn btn-secondary btn-sm" onClick={async () => {
                        startLoading('Generating Summary...');
                        const res = await summary.summarizeText(rec.transcript, 'summary');
                        if (res) handleSummaryResult(rec, res, 'Summary');
                      }}>📝 Summary</button>
                      
                      <button className="btn btn-secondary btn-sm" onClick={async () => {
                        startLoading('Generating Study Notes...');
                        const res = await summary.summarizeText(rec.transcript, 'study');
                        if (res) handleSummaryResult(rec, res, 'Study Notes');
                      }}>📚 Study</button>
                    </>
                  )}
                  <button className="btn btn-outline btn-sm" style={{ color: 'var(--color-danger)' }} onClick={() => axios.delete(`http://localhost:3001/recordings/${rec.filename}`).then(() => fetchSavedRecordings())}>🗑️</button>
                </div>
              }
            />
            
            {rec.summary && (
              <div style={{ paddingLeft: '32px', position: 'relative' }}>
                <div style={{ position: 'absolute', left: '15px', top: '0', bottom: '0', width: '2px', background: 'var(--border-primary)' }}></div>
                <FeedCard
                  avatar="🧠"
                  title={getSummaryTitle(rec.summary, rec._id)}
                  subtitle="AI Generated Summary"
                  fullText={rec.summary}
                  actions={
                    <>
                      <button className="btn btn-outline btn-sm" onClick={() => copyToClipboard(rec.summary)}>📋 Copy</button>
                      <button className="btn btn-primary btn-sm" onClick={() => exportToPDF(rec.summary, getSummaryTitle(rec.summary, rec._id))}>📄 PDF</button>
                    </>
                  }
                />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default TranscriptView;
